In [1]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris

# Load dataset
iris = load_iris()

# Create DataFrame
df = pd.DataFrame(data=iris.data, columns=iris.feature_names)

# Add species column
df['species'] = iris.target

df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),species
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0

In [2]:
# Mean
print("Mean:\n", df.mean(numeric_only=True))

# Median
print("\nMedian:\n", df.median(numeric_only=True))

# Minimum
print("\nMinimum:\n", df.min(numeric_only=True))

# Maximum
print("\nMaximum:\n", df.max(numeric_only=True))

# Standard Deviation
print("\nStandard Deviation:\n", df.std(numeric_only=True))

Mean:
 sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
species              1.000000
dtype: float64

Median:
 sepal length (cm)    5.80
sepal width (cm)     3.00
petal length (cm)    4.35
petal width (cm)     1.30
species              1.00
dtype: float64

Minimum:
 sepal length (cm)    4.3
sepal width (cm)     2.0
petal length (cm)    1.0
petal width (cm)     0.1
species              0.0
dtype: float64

Maximum:
 sepal length (cm)    7.9
sepal width (cm)     4.4
petal length (cm)    6.9
petal width (cm)     2.5
species              2.0
dtype: float64

Standard Deviation:
 sepal length (cm)    0.828066
sepal width (cm)     0.435866
petal length (cm)    1.765298
petal width (cm)     0.762238
species              0.819232
dtype: float64

In [3]:
df.describe()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),species
count,150.000000,150.000000,150.000000,150.000000,150.000000
mean,5.843333,3.057333,3.758000,1.199333,1.000000
std,0.828066,0.435866,1.765298,0.762238,0.819232
min,4.300000,2.000000,1.000000,0.100000,0.000000
25%,5.100000,2.800000,1.600000,0.300000,0.000000
50%,5.800000,3.000000,4.350000,1.300000,1.000000
75%,6.400000,3.300000,5.100000,1.800000,2.000000
max,7.900000,4.400000,6.900000,2.500000,2.000000

In [4]:
# Group by species and calculate mean
df.groupby('species').mean()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
species,,,,
0,5.006,3.428,1.462,0.246
1,5.936,2.770,4.260,1.326
2,6.588,2.974,5.552,2.026

In [5]:
# Group by and calculate multiple statistics
df.groupby('species').agg(['mean', 'median', 'min', 'max', 'std'])

        sepal length (cm)                            sepal width (cm)         \
                     mean median  min  max       std             mean median
species
0                   5.006    5.0  4.3  5.8  0.352490            3.428    3.4
1                   5.936    5.9  4.9  7.0  0.516171            2.770    2.8
2                   6.588    6.5  4.9  7.9  0.635880            2.974    3.0

                            petal length (cm)                             \
         min  max       std              mean median  min  max       std
species
0        2.3  4.4  0.379064             1.462   1.50  1.0  1.9  0.173664
1        2.0  3.4  0.313798             4.260   4.35  3.0  5.1  0.469911
2        2.2  3.8  0.322497             5.552   5.55  4.5  6.9  0.551895

        petal width (cm)
                    mean median  min  max       std
species
0                  0.246    0.2  0.1  0.6  0.105386
1                  1.326    1.3  1.0  1.8  0.197753
2                  2.026    2.0  1.4  2.5  0.274650

In [6]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

# Convert species to string first (for proper demo)
df['species_str'] = df['species'].astype(str)

# Apply label encoding
df['species_encoded'] = le.fit_transform(df['species_str'])

df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),species,species_str,species_encoded
0,5.1,3.5,1.4,0.2,0,0,0
1,4.9,3.0,1.4,0.2,0,0,0
2,4.7,3.2,1.3,0.2,0,0,0
3,4.6,3.1,1.5,0.2,0,0,0
4,5.0,3.6,1.4,0.2,0,0,0

In [7]:
# One-hot encoding
df_onehot = pd.get_dummies(df, columns=['species'])

df_onehot.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),species_str,species_encoded,species_0,species_1,species_2
0,5.1,3.5,1.4,0.2,0,0,True,False,False
1,4.9,3.0,1.4,0.2,0,0,True,False,False
2,4.7,3.2,1.3,0.2,0,0,True,False,False
3,4.6,3.1,1.5,0.2,0,0,True,False,False
4,5.0,3.6,1.4,0.2,0,0,True,False,False

In [8]:
# Separate data for each species
setosa = df[df['species'] == 0]
versicolor = df[df['species'] == 1]
virginica = df[df['species'] == 2]

print("Setosa:\n", setosa.head())
print("\nVersicolor:\n", versicolor.head())
print("\nVirginica:\n", virginica.head())

Setosa:
    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

   species species_str  species_encoded
0        0           0                0
1        0           0                0
2        0           0                0
3        0           0                0
4        0           0                0

Versicolor:
     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
50                7.0               3.2                4.7               1.4
51                6.4               3.2                4.5               1.5
52                6.9               3.1                4.9               1.5
53                5.5               2.3                4.0               1.3
54                6.5               2.8                4.6               1.5

    species species_str  species_encoded
50        1           1                1
51        1           1                1
52        1           1                1
53        1           1                1
54        1           1                1

Virginica:
      sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
100                6.3               3.3                6.0               2.5
101                5.8               2.7                5.1               1.9
102                7.1               3.0                5.9               2.1
103                6.3               2.9                5.6               1.8
104                6.5               3.0                5.8               2.2

     species species_str  species_encoded
100        2           2                2
101        2           2                2
102        2           2                2
103        2           2                2
104        2           2                2

In [9]:
# Statistics for each species

print("Setosa Stats:\n", setosa.describe())
print("\nVersicolor Stats:\n", versicolor.describe())
print("\nVirginica Stats:\n", virginica.describe())

Setosa Stats:
        sepal length (cm)  sepal width (cm)  petal length (cm)  \
count           50.00000         50.000000          50.000000
mean             5.00600          3.428000           1.462000
std              0.35249          0.379064           0.173664
min              4.30000          2.300000           1.000000
25%              4.80000          3.200000           1.400000
50%              5.00000          3.400000           1.500000
75%              5.20000          3.675000           1.575000
max              5.80000          4.400000           1.900000

       petal width (cm)  species  species_encoded
count         50.000000     50.0             50.0
mean           0.246000      0.0              0.0
std            0.105386      0.0              0.0
min            0.100000      0.0              0.0
25%            0.200000      0.0              0.0
50%            0.200000      0.0              0.0
75%            0.300000      0.0              0.0
max            0.600000      0.0              0.0

Versicolor Stats:
        sepal length (cm)  sepal width (cm)  petal length (cm)  \
count          50.000000         50.000000          50.000000
mean            5.936000          2.770000           4.260000
std             0.516171          0.313798           0.469911
min             4.900000          2.000000           3.000000
25%             5.600000          2.525000           4.000000
50%             5.900000          2.800000           4.350000
75%             6.300000          3.000000           4.600000
max             7.000000          3.400000           5.100000

       petal width (cm)  species  species_encoded
count         50.000000     50.0             50.0
mean           1.326000      1.0              1.0
std            0.197753      0.0              0.0
min            1.000000      1.0              1.0
25%            1.200000      1.0              1.0
50%            1.300000      1.0              1.0
75%            1.500000      1.0              1.0
max            1.800000      1.0              1.0

Virginica Stats:
        sepal length (cm)  sepal width (cm)  petal length (cm)  \
count           50.00000         50.000000          50.000000
mean             6.58800          2.974000           5.552000
std              0.63588          0.322497           0.551895
min              4.90000          2.200000           4.500000
25%              6.22500          2.800000           5.100000
50%              6.50000          3.000000           5.550000
75%              6.90000          3.175000           5.875000
max              7.90000          3.800000           6.900000

       petal width (cm)  species  species_encoded
count          50.00000     50.0             50.0
mean            2.02600      2.0              2.0
std             0.27465      0.0              0.0
min             1.40000      2.0              2.0
25%             1.80000      2.0              2.0
50%             2.00000      2.0              2.0
75%             2.30000      2.0              2.0
max             2.50000      2.0              2.0

In [11]:
print("Setosa Percentiles:\n", setosa.quantile([0.25, 0.5, 0.75], numeric_only=True))

Setosa Percentiles:
       sepal length (cm)  sepal width (cm)  petal length (cm)  \
0.25                4.8             3.200              1.400
0.50                5.0             3.400              1.500
0.75                5.2             3.675              1.575

      petal width (cm)  species  species_encoded
0.25               0.2      0.0              0.0
0.50               0.2      0.0              0.0
0.75               0.3      0.0              0.0