In [1]:
import pandas as pd
import numpy as np

In [2]:
import pandas as pd

data = {
    'Age_Group': ['Young', 'Young', 'Adult', 'Adult', 'Senior', 'Senior', 'Young', 'Adult'],
    'Income': [20000, 22000, 30000, 32000, 25000, 27000, 21000, 31000]
}

df = pd.DataFrame(data)
df

  Age_Group  Income
0     Young   20000
1     Young   22000
2     Adult   30000
3     Adult   32000
4    Senior   25000
5    Senior   27000
6     Young   21000
7     Adult   31000

In [3]:
grouped_stats = df.groupby('Age_Group')['Income'].agg(['mean', 'median', 'min', 'max', 'std'])
grouped_stats

              mean   median    min    max          std
Age_Group
Adult      31000.0  31000.0  30000  32000  1000.000000
Senior     26000.0  26000.0  25000  27000  1414.213562
Young      21000.0  21000.0  20000  22000  1000.000000

In [4]:
from sklearn.preprocessing import OneHotEncoder

enc = OneHotEncoder()
encoded = enc.fit_transform(df[['Age_Group']]).toarray()

enc_df = pd.DataFrame(encoded)
enc_df

     0    1    2
0  0.0  0.0  1.0
1  0.0  0.0  1.0
2  1.0  0.0  0.0
3  1.0  0.0  0.0
4  0.0  1.0  0.0
5  0.0  1.0  0.0
6  0.0  0.0  1.0
7  1.0  0.0  0.0

In [5]:
df_final = df.join(enc_df)
df_final

  Age_Group  Income    0    1    2
0     Young   20000  0.0  0.0  1.0
1     Young   22000  0.0  0.0  1.0
2     Adult   30000  1.0  0.0  0.0
3     Adult   32000  1.0  0.0  0.0
4    Senior   25000  0.0  1.0  0.0
5    Senior   27000  0.0  1.0  0.0
6     Young   21000  0.0  0.0  1.0
7     Adult   31000  1.0  0.0  0.0